service: sentence-similarity-efs

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  timeout: 120
  environment:
   PYTHONPATH: "/mnt/tmp/lib"



functions:
  hello:
    handler: handler.hello
    fileSystemConfig:
      localMountPath: /mnt/tmp
      arn: arn:aws:elasticfilesystem:us-east-1:************:access-point/fsap-08c6b99eba84f318e
    vpc:
      securityGroupIds:
        - sg-********
      subnetIds:
        - subnet-********
        - subnet-********
        - subnet-********
