service: s3-trigger-event

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  timeout: 120
  layers:
        - arn:aws:lambda:us-east-1:931955206531:layer:pandas-numpy:1
        - arn:aws:lambda:us-east-1:931955206531:layer:s3fs:3

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: 
       - 'arn:aws:s3:::serverless-s3trigger-demo/*'
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:931955206531:table/s3trigger_serverless


functions:
  hello:
    handler: handler.hello
    events:
        - s3:
            bucket: serverless-s3trigger-demo
            event: s3:ObjectCreated:*
            rules:
              - prefix: media-files/
              - suffix: .csv
            existing: true
