service: serverless-demo-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  layers:
        - arn:aws:lambda:us-east-1:931955206531:layer:python-pandas:1

plugins:
  - serverless-python-requirements

# serverless python requirements: https://www.serverless.com/plugins/serverless-python-requirements
# used the code upto usestaticCache if you want to use external libraries in requirements.txt ; the code in layer tag can be used to push AWS lambda layer
# custom:
#   pythonRequirements:
#     dockerizePip: true
#     zip: true
#     useDownloadCache: false
#     useStaticCache: false

#     layer: 
#       name: python-pandas
#       description: "Layer which contains pandas library"
#       compatibleRuntimes:
#         - python3.8

functions:
  hello:
    handler: handler.hello
  

package:
  patterns:
    - '!**/*'
    - '*.py'
    - 'pandas'
